import {chromium} from '@playwright/test';
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const server=http.createServer(async(req,res)=>{try{const name=req.url==='/'?'index.html':req.url.split('?')[0].slice(1);if(name.includes('..'))throw Error();const buf=await fs.readFile(path.join(process.cwd(),'public',name));res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(buf);}catch{res.statusCode=404;res.end();}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
let saved=null,revision=0,conflict=false;const errors=[];
const user={id:'11111111-1111-4111-8111-111111111111',aud:'authenticated',role:'authenticated',email:'baker@example.com',created_at:new Date().toISOString()};
const token='eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({sub:user.id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.signature';
async function context(width,height){const c=await browser.newContext({viewport:{width,height}});await c.route('**/config.js',r=>r.fulfill({contentType:'text/javascript',body:'window.COOKIE_CONFIG={url:"https://example.supabase.co",key:"sb_publishable_test"};'}));await c.route('https://example.supabase.co/**',async r=>{const url=new URL(r.request().url());let data;if(url.pathname.includes('/token'))data={access_token:token,refresh_token:'test',expires_in:3600,token_type:'bearer',user};else if(url.pathname.includes('/user'))data=user;else if(url.pathname.includes('/bakers'))data=[{user_id:user.id}];else if(url.pathname.includes('/rpc/save_kitchen')){if(conflict)return r.fulfill({status:409,contentType:'application/json',body:JSON.stringify({code:'40001',message:'Kitchen revision conflict'})});const body=r.request().postDataJSON();assert.equal(body.expected_revision,revision);saved=structuredClone(body.kitchen_data);revision++;data={revision};}else if(url.pathname.includes('/kitchens'))data=saved?[{data:saved,revision}]:[];else data={};await r.fulfill({contentType:'application/json',body:JSON.stringify(data)});});return c;}
try{
 const desktop=await context(1440,1000),page=await desktop.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('heading',{name:'Cookie Season',exact:true}).waitFor();assert.equal(await page.locator('.app').isVisible(),false);await page.locator('[name=email]').fill('baker@example.com');await page.locator('[name=password]').fill('long-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();await page.getByText('Saved',{exact:true}).waitFor();
 await page.getByRole('button',{name:'＋ Add request',exact:true}).click();await page.locator('#request-form [name=name]').fill('Test Household');await page.locator('#request-form [name=home]').selectOption('OH');await page.locator('#request-form [name="r-0"]').fill('25');await page.getByRole('button',{name:'Save request',exact:true}).click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.requests[0].home,'OH');assert.equal(saved.requests[0].items[0],25);
 await page.locator('#nav [data-go=bake]').click();await page.getByRole('heading',{name:'Bake plan',exact:true}).waitFor();await page.locator('[data-assign="0"]').first().click();await page.locator('[name=oh]').fill('2');await page.locator('#location-form .btn').last().click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.batchAssignments[0].OH,2);
 await page.locator('#nav [data-go=ingredients]').click();await page.locator('[data-stock-id="10"][data-stock-home="OH"]').fill('10');await page.locator('[data-stock-id="10"][data-stock-home="OH"]').press('Tab');await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.ingredients.find(i=>i.id===10).stock.OH,10);
 await page.evaluate(()=>{state.ingredients.forEach(i=>i.stock.OH=100);persist();});await page.getByText('Saved',{exact:true}).waitFor();
 await page.locator('#nav [data-go=bake]').click();await page.getByRole('button',{name:'Record baking',exact:true}).click();await page.locator('[name=recipe]').selectOption('0');await page.locator('[name=home]').selectOption('OH');await page.locator('[name=store]').selectOption('WV');await page.locator('[name=batches]').fill('2');await page.locator('#location-form .btn').last().click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.movements.at(-1).cookies,36);assert.equal(saved.movements.at(-1).storeHome,'WV');assert(saved.ingredients.find(i=>i.id===10).stock.OH<100);
 await page.locator('#nav [data-go=freezers]').click();await page.getByRole('button',{name:'Transfer stock',exact:true}).click();await page.locator('[name=item]').selectOption('r:0');await page.locator('[name=quantity]').fill('25');await page.locator('#location-form .btn').last().click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.movements.at(-1).kind,'cookie-transfer');
 await page.locator('#nav [data-go=requests]').click();await page.getByRole('button',{name:'Details →',exact:true}).click();await page.getByRole('button',{name:'Record handoff',exact:true}).click();await page.locator('#location-form .btn').last().click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.requests[0].status,'Handed over');assert.equal(saved.movements.at(-1).quantity,25);
 await page.locator('#nav [data-go=freezers]').click();await page.getByRole('button',{name:'Record donation',exact:true}).click();await page.locator('[name=recipe]').selectOption('0');await page.locator('[name=quantity]').fill('11');await page.locator('[name=destination]').fill('School');await page.locator('#location-form .btn').last().click();await page.getByText('Saved',{exact:true}).waitFor();assert.equal(saved.movements.at(-1).kind,'donation');
 for(const v of ['overview','requests','bake','shopping','recipes','ingredients','freezers','settings']){await page.locator('#nav [data-go='+v+']').click();await page.waitForTimeout(50);const text=await page.locator('#main').innerText();assert(!/v18|workbook|concept preview|Invited guest/i.test(text),v);assert(!/NaN|undefined|Infinity/.test(text),v);}
 await page.locator('#nav [data-go=overview]').click();await page.screenshot({path:'/workspace/scratch/c408fa3719d7/cookie-desktop.png',fullPage:true});
 const mobile=await context(390,844),phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://127.0.0.1:'+server.address().port);await phone.locator('[name=email]').fill('baker@example.com');await phone.locator('[name=password]').fill('long-password');await phone.getByRole('button',{name:'Sign in',exact:true}).click();await phone.getByRole('heading',{name:'Overview',exact:true}).waitFor();await phone.locator('#mobile-menu-toggle').click();assert.equal(await phone.locator('#mobile-menu-toggle').getAttribute('aria-expanded'),'true');await phone.locator('#nav [data-go=freezers]').click();assert.equal(await phone.locator('#mobile-current-page').innerText(),'Freezers');await phone.screenshot({path:'/workspace/scratch/c408fa3719d7/cookie-mobile.png',fullPage:true});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 conflict=true;await page.locator('#nav [data-go=ingredients]').click();await page.locator('[data-stock-id="10"][data-stock-home="OH"]').fill('11');await page.locator('[data-stock-id="10"][data-stock-home="OH"]').press('Tab');await page.getByText('Download my changes',{exact:true}).waitFor();assert.equal(saved.ingredients.find(i=>i.id===10).stock.OH<100,true);assert((await page.locator('#sync-error').innerText()).includes('Another device'));assert.equal(errors.length,0,errors.join('\n'));
 console.log('Passed browser checks: gated sign-in, manual OH request, batch assignments, home pantry persistence, baking, freezer transfer, handoff, donation, eight views, mobile navigation/overflow, and conflict recovery. Backend responses were mocked.');
}finally{await browser.close();server.close();}
